language: go
sudo: required
dist: xenial

go:
  - 1.x
env:
- GO111MODULE=on
script:
  # Install wireguard
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y ppa:wireguard/wireguard
  - sudo apt-get -y update
  - sudo apt-get -y install linux-headers-$(uname -r) wireguard-dkms ipset
  - sudo ip link add wg0 type wireguard
  - sudo ip link set up wg0
  # Build the project and run the tests
  - make
  # Set up iptables
  - sudo iptables -t nat -N PORTFORWARDING
  - sudo ip6tables -t nat -N PORTFORWARDING
  - sudo ipset create PORTFORWARDING_IPV4 hash:ip
  - sudo ipset create PORTFORWARDING_IPV6 hash:ip family inet6
  # Build the integration tests
  - go test -c ./portforward && go test -c ./wireguard
  # Run integration tests
  - sudo ./portforward.test -test.v && sudo ./wireguard.test -test.v

notifications:
  email:
    on_success: never
    on_failure: never
