language: go
sudo: required
dist: xenial

go:
  - 1.x
env:
- GO111MODULE=on
script:
  # Install cavpn
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y ppa:cavpn/cavpn
  - sudo apt-get -y update
  - sudo apt-get -y install linux-headers-$(uname -r) cavpn-dkms ipset
  - sudo ip link add cv0 type cavpn
  - sudo ip link set up cv0
  # Build the project and run the tests
  - make
  # Set up iptables
  - sudo iptables -t nat -N PORTFORWARDING
  - sudo ip6tables -t nat -N PORTFORWARDING
  - sudo ipset create PORTFORWARDING_IPV4 hash:ip
  - sudo ipset create PORTFORWARDING_IPV6 hash:ip family inet6
  # Build the integration tests
  - go test -c ./portforward && go test -c ./cavpn
  # Run integration tests
  - sudo ./portforward.test -test.v && sudo ./cavpn.test -test.v

notifications:
  email:
    on_success: never
    on_failure: never
